# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8274ce795d9530cf9cf2b0a4fb7bf57be8965b29c3706eee7a17de686d4d7bc9bc00568877c686e1dc060a8f6cceabc8b65d2d1bf1463cacdf1fa08f84bdfe28

test:
  secret_key_base: 170d5003f54239e4e18436574f9ca43e1c4d92033a105c039787db8e3b4fd909ba2d120ecd52ce4c5f9a4f07f6f10485dfdf34cabcb9d0bab0eec53fe1ef48e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
